CREATE TABLE jugadores (
    jugador_id INT PRIMARY KEY AUTO_INCREMENT,
    nombre_usuario VARCHAR(50) NOT NULL,
    tiempo_total_jugado BIGINT DEFAULT 0, 
    salud FLOAT DEFAULT 20,  
    fecha_registro DATETIME DEFAULT CURRENT_TIMESTAMP, 
    ultima_actividad DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
);