CREATE TABLE mob_pass( 
  ID INT PRIMARY KEY AUTO_INCREMENT,
  Nombre_pass VARCHAR(50) NOT NULL,
  loot VARCHAR(50) NOT NULL,
  loot_exp BOOLEAN NOT NULL,
  vida DECIMAL,
  movilidad VARCHAR(50) NOT NULL,
  reproduccion BOOLEAN NOT NULL
)

