<<<<<<< HEAD
CREATE TABLE mob_pass( 
  ID INT PRIMARY KEY AUTO_INCREMENT,
  Nombre_pass VARCHAR(50) NOT NULL,
  loot VARCHAR(50) NOT NULL,
  loot_exp BOOLEAN NOT NULL,
  vida DECIMAL,
  movilidad VARCHAR(50) NOT NULL,
  reproduccion BOOLEAN NOT NULL
)
=======
CREATE TABLE Mob_pass( 
  ID INT PRIMARY KEY AUTO_INCREMENT,
  nombre_pass VARCHAR(50) NOT NULL,
  loot VARCHAR(50) NOT NULL,
  loot_exp BOOLEAN NOT NULL,
  vida DECIMAL,
  reproduccion BOOLEAN NOT NULL,
  movilidad VARCHAR(50) NOT NULL
);
>>>>>>> 09e645061ed897332d8b797541bd0d4e27e93be6
