INSERT INTO Comida (nombre_comida, efecto, recuperar_hambre, recuperar_vida, receta)
    VALUES 
    ("Ojo de araña", "veneno", 0.0, 0.0, "Vacio"),
    ("Pez globo", "veneno, hambre", 2.0, 1.0, "Vacio"),
    ("Carne podrida", "hambre", 4.0, 2.0, "Vacio"),
    ("Galleta", "", 2.0, 2.0, "Trigo, Semillas de cacao"),
    ("Tarta", "Vacio", 2.0, 3.0, "Cubo con leche, Azúcar, Huevo, Trigo"),
    ("Sandia", "Vacio", 2.5, 3.0, "Rodaja de sandía"),
    ("Patata venenoza", "veneno", 1.0, 1.0, "Vacio"),
    ("Manzana", "Vacio", 2.0, 2.0, ""),
    ("Tarta de calabaza", "", 8.0, 4.0, "Calabaza, Azúcar, Huevo"),
    ("Zanahoria", "Vacio", 4.0, 2.0, "Vacio"),
    ("Bacalao cocinado", "Vacio", 5.0, 3.0, "Bacalao crudo, Cualquier combustible"),
    ("Pan", "Vacio", 5.0, 3.0, "Bacalao crudo, Cualquier combustible"),
    ("Estofado sospechoso", "hambre", 6.0, 3.0, "Champiñón rojo, Champiñón marrón, Cuenco, Diente de león o Amapola o Orquídea azul o Allium o Aciano o Tulipán rojo o Tulipán naranja o Tulipán blanco o Tulipán rosa o Margarita o Girasol o Lila o Rosal o Peonía"),
    ("Estofado de champiñones", "Vacio", 6.0, 3.0, "Champiñón rojo, Champiñón marrón, Cuenco"),
    ("Estofado de remolacha", "Vacio", 6.0, 3.0, "Remolacha, Cuenco"),
    ("Estofado de conejo", "Vacio", 10.0, 12.0, "Conejo cocinado, Zanahoria, Patata cocida, Champiñón rojo o Champiñón marrón, Cuenco"),
    ("Remolacha", "Vacio", 1.0, 1.0, "Vacio"),
    ("Conejo asado", "Vacio", 5.0, 6.0, "Conejo crudo, Cualquier combustible"),
    ("Pollo asado", "Vacio", 6.0, 5.0, "Pollo crudo, Cualquier combustible"),
    ("Patata cocinada", "Vacio", 6.0, 5.0, "Patata, Cualquier combustible"),
    ("Salmon ahumado", "Vacio", 6.0, 6.0, "Salmón crudo, Cualquier combustible"),
    ("Filete asado", "Vacio", 6.0, 5.0, "Filete crudo, Cualquier combustible"),
    ("Chuleta de cerdo cocinado", "Vacio", 6.0, 6.0, "chuleta de cerdo crudo, Cualquier combustible"),
    ("Zanahoria dorada", "curacion", 3.0, 6.0, "Pepita de oro, Zanahoria"),
    ("Manzana dorada", "Absorción, Regeneración ", 4.0, 4.0, "Lingote de oro, Manzana"),
    ("Manzana dorada encantada", "Absorción, Regeneración, Cuerpo ignífugo, Resistencia", 4.0, 8.0, "Bloques de oro, Manzana");
